#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine and installs ngnx
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
sed -i " /listen 80 default_server;/a rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
