#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine and installs ngnx
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
