#!/usr/bin/env bash
#configure costum http header response in nginx
# this also can be "20i add_header X-Served-By $HOSTNAME;" must specify the line
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy=1.8.\*
echo -e "\nfrontend victorz94.tech\n\tbind *:80\n\tmode http\n\tdefault_backend webservers" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend webservers\n\tbalance roundrobin\n\tserver 1484-web-01 35.237.76.6:80 check\n\tserver 1484-web-02 35.229.51.65:80 check\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy  restart
