#!/usr/bin/env bash
# read, filter etc/passwd

FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
echo "$username:$userid:$homedir"
done < $FILENAME
