#!/usr/bin/env bash
# print ls and use cut

FILE=holbertonschool
if [ -a $FILE ]
then
	echo "$FILE file exists"
	if [ -s $FILE ]
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
	if [ -f $FILE ]
	then
		echo "$FILE is a regular file" 
	fi
else
	echo "$FILE file does not exist"
fi
